# Generated by Django 3.0.5 on 2020-05-04 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentType', models.CharField(choices=[('1', 'Text (Plain)'), ('2', 'Text (HTML FORMAT)'), ('3', 'External Video'), ('4', 'External Document')], error_messages={'blank': 'you must select the type of content.', 'null': 'you must select the type of content.'}, help_text='select the type of content.', max_length=2, verbose_name='country')),
                ('contenttextPlain', models.TextField(blank=True, help_text='entry only content plain text', null=True, verbose_name='Plain text')),
                ('contenttextHTML', models.TextField(blank=True, help_text='entry content in HTML format', null=True, verbose_name='HTML format text')),
                ('contentExternalVideo', models.CharField(blank=True, help_text='entry only url', max_length=300, null=True, verbose_name='External Video')),
                ('contentExternalDocument', models.CharField(blank=True, help_text='entry only Url', max_length=300, null=True, verbose_name='Plain text')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 200 characters or fewer.', max_length=200, verbose_name='course name')),
                ('description', models.TextField()),
                ('learn', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 120 characters or fewer.', max_length=120, verbose_name='Module name')),
                ('segments', models.IntegerField(default=0, help_text='number of segments in a module', verbose_name='number of segments in a module')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 120 characters or fewer.', max_length=120, verbose_name='segment name')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('module', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.Module')),
            ],
        ),
    ]
