# Generated by Django 3.0.6 on 2020-05-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200504_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='contentExternalDocument',
        ),
        migrations.RemoveField(
            model_name='content',
            name='contentExternalVideo',
        ),
        migrations.RemoveField(
            model_name='content',
            name='contenttextHTML',
        ),
        migrations.RemoveField(
            model_name='content',
            name='contenttextPlain',
        ),
        migrations.AddField(
            model_name='content',
            name='content',
            field=models.TextField(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='contentType',
            field=models.CharField(choices=[('1', 'Text (Plain)'), ('2', 'Text (HTML FORMAT)'), ('3', 'External Video'), ('4', 'External Document')], error_messages={'blank': 'you must select the type of content.', 'null': 'you must select the type of content.'}, help_text='select the type of content.', max_length=2, verbose_name='content type'),
        ),
    ]
