# Generated by Django 3.0.6 on 2020-05-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200521_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='segments',
            field=models.IntegerField(help_text='number of segments in a module', verbose_name='number of segments in a module'),
        ),
    ]
