# Generated by Django 3.0.6 on 2020-05-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200522_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(help_text='Required. 120 characters or fewer.', max_length=120, verbose_name='content name'),
        ),
    ]
