# Generated by Django 3.0.6 on 2020-06-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200531_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Required. 1500 characters or fewer.', max_length=1500, verbose_name='course description'),
        ),
    ]
