# Generated by Django 3.0.6 on 2020-06-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200601_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='date_create',
            new_name='create_date',
        ),
    ]
