# Generated by Django 3.0.6 on 2020-06-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='banner',
        ),
    ]
