# Generated by Django 3.0.6 on 2020-06-07 08:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0017_usercourserelations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCourseRelations',
            new_name='CourseUserRelations',
        ),
    ]
