# Generated by Django 3.0.6 on 2020-06-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20200610_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.ImageField(blank=True, default='default_banner.png', help_text='maxime zise of 2MB. JPG ó PNG.', upload_to='banner_pics/', verbose_name='banner image'),
        ),
    ]
