# Generated by Django 3.0.6 on 2020-06-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20200610_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contentType',
            field=models.CharField(choices=[('1', 'Text (Plain)'), ('2', 'Text (HTML FORMAT)'), ('3', 'External Video'), ('4', 'External Document'), ('5', 'Exam')], error_messages={'blank': 'you must select the type of content.', 'null': 'you must select the type of content.'}, help_text='select the type of content.', max_length=2, verbose_name='content type'),
        ),
    ]
