# Generated by Django 3.0.6 on 2020-06-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20200612_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='contentType',
            new_name='content_type',
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(default='1', verbose_name='Content'),
        ),
    ]
