# Generated by Django 3.0.6 on 2020-06-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200522_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, default='Universidad de Carabobo', error_messages={'null': 'you must enter your University.'}, max_length=70, verbose_name='university'),
        ),
        migrations.AlterField(
            model_name='user',
            name='academic_degree',
            field=models.CharField(blank=True, error_messages={'null': 'you must enter your academic degree.'}, max_length=70, verbose_name='academic degree'),
        ),
    ]
