# Generated by Django 3.0.6 on 2020-06-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200602_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='avatar_pics', verbose_name='Avatar image'),
        ),
    ]
