# Generated by Django 3.0.6 on 2020-06-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200604_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.png', help_text='maxime zise of 1MB. JPG ó PNG.', upload_to='avatar_pics/', verbose_name='Avatar image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='twitter'),
        ),
    ]
