# Generated by Django 3.0.6 on 2020-06-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200605_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', help_text='maxime zise of 1MB. JPG ó PNG.', upload_to='avatar_pics/', verbose_name='Avatar image'),
        ),
    ]
