# Generated by Django 3.0.6 on 2020-06-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200618_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='teacher',
        ),
    ]
