# Generated by Django 3.0.6 on 2020-06-25 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
