# Generated by Django 3.0.6 on 2020-05-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quiz',
            new_name='exam',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='exam',
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(help_text='Required. 150 characters or fewer.', max_length=150, verbose_name='Exam name'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(error_messages={'unique': 'A question with that name already exists.'}, help_text='Required. 600 characters or fewer.', max_length=600, verbose_name='question'),
        ),
    ]
