# Generated by Django 3.0.6 on 2020-06-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20200531_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='date_create',
            new_name='create_data',
        ),
    ]
