# Generated by Django 3.0.6 on 2020-06-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20200603_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
