# Generated by Django 3.0.6 on 2020-06-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_userexamrelations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexamrelations',
            name='lastTry',
            field=models.DateTimeField(default=None),
        ),
    ]
