# Generated by Django 3.0.6 on 2020-06-07 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20200605_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexamrelations',
            name='points',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
