# Generated by Django 3.0.6 on 2020-06-07 08:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0007_auto_20200607_0840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExamRelations',
            new_name='ExamUserRelations',
        ),
    ]
