# Generated by Django 3.0.6 on 2020-06-11 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_auto_20200607_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='module',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='segment',
        ),
    ]
