# Generated by Django 3.0.6 on 2020-06-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_examuserrelations_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examuserrelations',
            name='userAnswer',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
