# Generated by Django 3.0.6 on 2020-06-13 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_auto_20200613_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='approved',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Put here the minimum points necessary to pass this exam.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='minimun points to approved'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionValue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='point value of the question.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='question grade'),
        ),
    ]
