# Generated by Django 3.0.6 on 2020-06-13 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_auto_20200613_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='approved',
            field=models.DecimalField(decimal_places=2, default=None, error_messages={'blank': 'you must provied the minimun points.', 'null': 'you must provied the minimun points.'}, help_text='Put here the minimum points necessary to pass this exam. Max 5 digits: 3 for en integer part and 2 for decimal part', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='minimun points to approved'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionValue',
            field=models.DecimalField(decimal_places=2, default=None, error_messages={'blank': 'you must provied the point value.', 'null': 'you must provied the point value.'}, help_text='Max 5 digits: same as "minimun points to approved"', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='question points'),
        ),
    ]
