# Generated by Django 3.0.6 on 2020-06-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_auto_20200613_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examuserrelations',
            old_name='lastTry',
            new_name='last_try',
        ),
        migrations.RenameField(
            model_name='examuserrelations',
            old_name='numberOfTry',
            new_name='number_of_try',
        ),
        migrations.RenameField(
            model_name='examuserrelations',
            old_name='userAnswer',
            new_name='user_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionValue',
            new_name='question_value',
        ),
    ]
